# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Deploy 

on:
  workflow_dispatch:
  push:
    branches: [ "main", "integration", "releases/**", "feature/**" ]
  pull_request:
    branches: [ "main", "integration", "releases/**" ]
  release:
    types: [ "created" ]

env:
  GO_VERSION: 1.19
  CONTAINER_REGISTRY: ghcr.io

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go (v4 caches by default)
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run go vet
        run: go vet -v ./...
      
      - name: Run gofmt
        run: gofmt -l .

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3      

  
  test:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go (v4 caches by default)
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Test
        run: go test -v ./...


  build:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go (v4 caches by default)
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: go build -v ./...


  deploy-ghcr-io:
    if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'release'
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set RELEASE_VERSION variable
        run: echo "RELEASE_VERSION=$(echo $GITHUB_REF | rev | cut -d '/' -f1 | rev)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: "https://${{ env.CONTAINER_REGISTRY }}"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}:latest,${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}:${{ env.RELEASE_VERSION }}"
