# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Main

on:
  workflow_dispatch:
  push:
    branches: [ "releases/**" ]
  
env:
  GO_VERSION: 1.19
  CONTAINER_REGISTRY: ghcr.io

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...


  # https://github.com/marketplace/actions/build-and-push-docker-images
  deploy-ghcr-io:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set RELEASE_VERSION variable
        run: echo "RELEASE_VERSION=$(echo $GITHUB_REF | rev | cut -d '/' -f1 | rev)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: "https://${{ env.CONTAINER_REGISTRY }}"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}:latest,${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}:${{ env.RELEASE_VERSION }}"